apiVersion: v1
kind: Pod
metadata:
  labels:
    app: fs
  name: gop-fileserver
spec:
  containers:
  - name: fs
    image: kodekloud/fileserver
    volumeMounts:
    - name: data-store
      mountPath: /web
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc 
