apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal-mysql
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  strategy: {}
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        envFrom:
        - secretKeyRef:
           name: drupal-mysql-secret
        volumeMounts:
        - name: drupal-mysql-data
          mountPath: /var/lib/mysql
          subPath: dbdata
      volumes:
      - name: drupal-mysql-data
        persistentVolumeClaim:
          claimName: drupal-mysql-pvc
