apiVersion: v1
data:
  redis.conf: |-
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
    protected-mode no
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-04T19:51:49Z"
  name: redis-cluster-configmap
  namespace: default
  resourceVersion: "404"
  selfLink: /api/v1/namespaces/default/configmaps/redis-cluster-configmap
  uid: 489a92f5-4ec6-11eb-952d-0242ac110002
