apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cluster-service
  name: gop-fs-service
spec:
  ports:
  - name: client
    port: 6379
    targetPort: 6379
  - name: gossip
    port: 16379
    targetPort: 16379
  selector:
    app: redis-cluster
  type: ClusterIP
